Задачи 10 и 20 готовы
js-tasks-ru/vue-20240627_vad21im pull request #2
Opened 2024-07-22 11:39 UTC by Vad21im

2024-07-22 11:39 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-07-22 20:20 UTC, ShGKme requested changes
В `01-basics/20-weather` требуется воспользоваться объектным синтаксисом привязки класса.

2024-07-22 20:20 UTC, ShGKme commented on 01-basics/10-create-app/script.js
> +  template: `<div>{{date}}</div>`
У текстовой интерполяции принято добавлять пробелы: `{{ date }}`

2024-07-22 20:20 UTC, ShGKme commented on 01-basics/20-weather/WeatherApp.js
> +        <li class="weather-card" :class="!blackandwhite(item.current)?'weather-card--night':''">
Во Vue, когда требуется добавить класс по условию, принято использовать синтаксис привязки класса объектом. Объект явно описывает, какой класс по какому выражению требуется добавлять.

https://vuejs.org/guide/essentials/class-and-style.html#binding-to-objects 

Так явно видно, от чего зависит наличие каждого класса, в привычном для Vue разработчиков стиле и удобно добавлять новые классы. 

И не требуется делать `else` с пустой строкой в тернарном операторе.

2024-07-22 20:30 UTC, jsru-1 commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2024-07-22 20:31 UTC, Vad21im commented
Теперь все верно? и я там забыл <p>{{item}}</p> убрать

2024-07-23 22:08 UTC, ShGKme approved these changes
Принято

2024-07-23 22:09 UTC, merged